# Automatically generated by configure - do not modify
SRC_PATH=/home/zhangxiang/Downloads/op-tee2/OP-TEE/qemu/roms/vgabios
AS=as
CCAS=/usr/bin/ccache gcc
CC=/usr/bin/ccache gcc
BCC=bcc
CPP=/usr/bin/ccache gcc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
